apiVersion: v1
kind: Deployment
metadata:
  name: create-contact-consumer-pod
  labels:
    app: create-contact-consumer
spec:
  containers:
  - name: create-contact-consumer
    image: caiofabiogomes/tc-fiap-create-contact-consumer:latest
    ports:
    - containerPort: 8082
    env:
    - name: RABBITMQ_HOST
      valueFrom:
        configMapKeyRef:
          name: contacts-producer-configmap
          key: rabbitmq_host
    - name: CONNECTION_DATABASE
      valueFrom:
        configMapKeyRef:
          name: contacts-producer-configmap
          key: cn_db

