apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  #type: ClusteIP #padrao - só acessivel dentro do cluster
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672        
      targetPort: 5672
      nodePort: 31001    
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31002
