apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-contacts-deployment
  labels:
    app: update-contacts
  annotations:
    type: "consumer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update-contacts
  template:
    metadata:
      labels:
        app: update-contacts
    spec:
      containers:
      - name: update-contacts
        image: caiofabiogomes/tc-fiap-consumer-update:latest
        ports:
        - containerPort: 8082
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: update-contacts-configmap
              key: rabbitmq_host
        - name: CONNECTION_DATABASE
          valueFrom:
            configMapKeyRef:
              name: update-contacts-configmap
              key: cn_db
