apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-contacts-deployment
  labels:
    app: create-contacts
  annotations:
    type: "consumer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-contacts
  template:
    metadata:
      labels:
        app: create-contacts
    spec:
      containers:
      - name: create-contacts
        image: caiofabiogomes/tc-fiap-create-contact-consumer:latest
        ports:
        - containerPort: 8082
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: create-contacts-configmap
              key: rabbitmq_host
        - name: CONNECTION_DATABASE
          valueFrom:
            configMapKeyRef:
              name: create-contacts-configmap
              key: cn_db
