apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-contacts-deployment
  labels:
    app: create-contacts
  annotations:
    type: "consumer"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: create-contacts
  template:
    metadata:
      labels:
        app: create-contacts
    spec:
      containers:
      - name: create-contacts
        image: caiofabiogomes/tc-fiap-create-contact-consumer:latest
        ports:
        - containerPort: 8082
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: create-contacts-configmap
              key: rabbitmq_host
        - name: CONNECTION_DATABASE
          valueFrom:
            configMapKeyRef:
              name: create-contacts-configmap
              key: cn_db
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: create-contacts-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: create-contacts
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70